// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CodebreakV2.Shared.Intercom {

  /// <summary>Holder for reflection information generated from auth.proto</summary>
  public static partial class AuthReflection {

    #region Descriptor
    /// <summary>File descriptor for auth.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgphdXRoLnByb3RvEhtDb2RlYnJlYWtWMi5TaGFyZWQuSW50ZXJjb20aDHNo",
            "YXJlZC5wcm90bzLmAQoLQXV0aFNlcnZpY2USXwoKQWNjb3VudEJhbhInLkNv",
            "ZGVicmVha1YyLlNoYXJlZC5JbnRlcmNvbS5CYW5SZXF1ZXN0GiguQ29kZWJy",
            "ZWFrVjIuU2hhcmVkLkludGVyY29tLkJhblJlc3BvbnNlEnYKDVdvcmxkUmVn",
            "aXN0ZXISMS5Db2RlYnJlYWtWMi5TaGFyZWQuSW50ZXJjb20uV29ybGRSZWdp",
            "c3RlclJlcXVlc3QaMi5Db2RlYnJlYWtWMi5TaGFyZWQuSW50ZXJjb20uV29y",
            "bGRSZWdpc3RlclJlc3BvbnNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CodebreakV2.Shared.Intercom.SharedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
