// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace CodebreakV2.Shared.Intercom {
  public static partial class WorldService
  {
    static readonly string __ServiceName = "CodebreakV2.Shared.Intercom.WorldService";

    static readonly grpc::Marshaller<global::CodebreakV2.Shared.Intercom.LoginTokenRequest> __Marshaller_LoginTokenRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CodebreakV2.Shared.Intercom.LoginTokenRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CodebreakV2.Shared.Intercom.LoginTokenResponse> __Marshaller_LoginTokenResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CodebreakV2.Shared.Intercom.LoginTokenResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::CodebreakV2.Shared.Intercom.LoginTokenRequest, global::CodebreakV2.Shared.Intercom.LoginTokenResponse> __Method_GenerateLoginToken = new grpc::Method<global::CodebreakV2.Shared.Intercom.LoginTokenRequest, global::CodebreakV2.Shared.Intercom.LoginTokenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateLoginToken",
        __Marshaller_LoginTokenRequest,
        __Marshaller_LoginTokenResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::CodebreakV2.Shared.Intercom.WorldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WorldService</summary>
    public abstract partial class WorldServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::CodebreakV2.Shared.Intercom.LoginTokenResponse> GenerateLoginToken(global::CodebreakV2.Shared.Intercom.LoginTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WorldService</summary>
    public partial class WorldServiceClient : grpc::ClientBase<WorldServiceClient>
    {
      /// <summary>Creates a new client for WorldService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WorldServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WorldService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WorldServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WorldServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WorldServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::CodebreakV2.Shared.Intercom.LoginTokenResponse GenerateLoginToken(global::CodebreakV2.Shared.Intercom.LoginTokenRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GenerateLoginToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::CodebreakV2.Shared.Intercom.LoginTokenResponse GenerateLoginToken(global::CodebreakV2.Shared.Intercom.LoginTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateLoginToken, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::CodebreakV2.Shared.Intercom.LoginTokenResponse> GenerateLoginTokenAsync(global::CodebreakV2.Shared.Intercom.LoginTokenRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GenerateLoginTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::CodebreakV2.Shared.Intercom.LoginTokenResponse> GenerateLoginTokenAsync(global::CodebreakV2.Shared.Intercom.LoginTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateLoginToken, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WorldServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WorldServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WorldServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GenerateLoginToken, serviceImpl.GenerateLoginToken).Build();
    }

  }
}
#endregion
