// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CodebreakV2.Shared.Intercom {

  /// <summary>Holder for reflection information generated from world.proto</summary>
  public static partial class WorldReflection {

    #region Descriptor
    /// <summary>File descriptor for world.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt3b3JsZC5wcm90bxIbQ29kZWJyZWFrVjIuU2hhcmVkLkludGVyY29tGgxz",
            "aGFyZWQucHJvdG8yhQEKDFdvcmxkU2VydmljZRJ1ChJHZW5lcmF0ZUxvZ2lu",
            "VG9rZW4SLi5Db2RlYnJlYWtWMi5TaGFyZWQuSW50ZXJjb20uTG9naW5Ub2tl",
            "blJlcXVlc3QaLy5Db2RlYnJlYWtWMi5TaGFyZWQuSW50ZXJjb20uTG9naW5U",
            "b2tlblJlc3BvbnNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CodebreakV2.Shared.Intercom.SharedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
